export default [
	{"theme_jp": "おたがいの名前", "question_en": "What's your name?", "responses": ["I'm Riko.", "Call me Riko.", "My name is Ito Jun."]},
	{"theme_jp": "スポーツ", "question_en": "Do you like sports?", "responses": ["Yes, I do.  I like badminton.", "No, I don't, but I like music."]},
	{"theme_jp": "卒業した小学校", "question_en": "Are you from Wakaba Elementary School?", "responses": ["Yes, I am.  How about you?", "No, I'm not.  I'm from Momiji Elementary School."]},
	{"theme_jp": "料理", "question_en": "Are you good at cooking?", "responses": ["Yes, I am.  I'm good at cooking yakisoba.", "No, I'm not.  How about you?"]},
	{"theme_jp": "ダンス", "question_en": "Can you dance well?", "responses": ["Yes, I can.  How about you?", "No, I can't, but I can sing well."]},
	{"theme_jp": "好きな動物", "question_en": "What animal do you like?", "responses": ["I like pandas.", "I like sea animals."]},
	{"theme_jp": "いちばん好きなテレビ番組", "question_en": "What's your favorite  TV program?", "responses": ["My favorite TV program is <em>Animal Friends</em>.", "Well, I don't watch TV."]},
	{"theme_jp": "誕生日", "question_en": "When's your birthday?", "responses": ["My birthday is July 20<sup>th</sup>."]},
	{"theme_jp": "住んでいる場所", "question_en": "Where do you live?", "responses": ["I live in Midori 2 <it>chome</it>.", "I live near Midori Station."]},
	{"theme_jp": "飼っているペット", "question_en": "Do you have any pets?", "responses": ["I have a cat.", "I don't have any pets."]},
	{"theme_jp": "好きな教科", "question_en": "What subject do you like?", "responses": ["I like P.E.", "My favorite subject is math."]},
	{"theme_jp": "町にあるもの", "question_en": "What can we see in your town?", "responses": ["You can see a big tower.", "You can see beautiful mountains."]},
	{"theme_jp": "きょうだいについて", "question_en": "Do you have any brothers or sisters?", "responses": ["Yes, I have a brother and two sisters.", "No, I don't.  I don't have any brothers or sisters."]},
	{"theme_jp": "好きなスポーツ", "question_en": "What sports do you like?", "responses": ["I like basketball and volleyball."]},
	{"theme_jp": "いちばん好きな料理", "question_en": "What's your favorite dish?", "responses": ["My favorite dish is chicken steak."]},
	{"theme_jp": "いちばん好きな歌手", "question_en": "Who's your favorite singer?", "responses": ["My favorite singer is Kenji.  I like him very much.  How about you?"]},
	{"theme_jp": "いちばん好きなアニメのキャラクター", "question_en": "Who's your favorite anime character?", "responses": ["My favorite anime character is Doraemon.", "I like Spongebob.  He is funny."]},
	{"theme_jp": "山派?海派?", "question_en": "Which do you like, the mountains or the sea?", "responses": ["I like the mountains.", "I like the sea.  I like swimming."]},
	{"theme_jp": "毎日のルーティーン", "question_en": "What's your daily routine?", "responses": ["I practice the piano every day.", "I walk my dog every day."]},
	{"theme_jp": "好きな本", "question_en": "What book do you like?", "responses": ["I like <em>Peter Pan</em>.", "I like <em>Beauty and the Beast</em>."]},
	{"theme_jp": "訪れたい国", "question_en": "What country do you want to visit?", "responses": ["I want to visit the U.K.", "I want to visit Brazil."]},
	{"theme_jp": "将来やりたいこと", "question_en": "What do you want to do in the future?", "responses": ["I want to travel around the world.", "I want to be a baseball player."]},
	{"theme_jp": "食べたいもの", "question_en": "What do you want to eat?", "responses": ["I want to eat Italian food.", "I want to eat some ethnic food."]},
	{"theme_jp": "水の使い方", "question_en": "How do you use water every day?", "responses": ["I wash my hands every day.", "I take a bath."]},
	{"theme_jp": "昨日食べたもの", "question_en": "What did you eat yesterday?", "responses": ["I had curry and rice.", "I ate fried noodles."]},
	{"theme_jp": "昨日見たテレビ番組", "question_en": "Did you watch TV yesterday?", "responses": ["Yes, I did.  I watched <em>Fishing Today</em>.", "No, I didn't.  How about you?"]},
	{"theme_jp": "日曜日にしたこと", "question_en": "What did you do last Sunday?", "responses": ["I went to the shopping mall.", "I cleaned my house."]},
	{"theme_jp": "週末の感想", "question_en": "How was your weekend?", "responses": ["It was great.  I watched a movie at my house.", "It was fun.  I went to Jiro's house."]},
	{"theme_jp": "昨日の午後８時にしていたこと", "question_en": "What were you doing at 8 p.m. yesterday?", "responses": ["I was reading a book.", "I was taking a shower."]},
	{"theme_jp": "家の近くのスーパーマーケット", "question_en": "Is there a supermarket near your house?", "responses": ["Yes, there is.  I often buy drinks there.", "No, there isn't, but there's a convenience store."]},
	{"theme_jp": "家の近くのコンビニエンスストア", "question_en": "Is there a convenience store near your house?", "responses": ["Yes, there's a 7-11.  I sometimes buy hot snacks there.  My favorite hot snack is the アメリカンドッグ."]},
	{"theme_jp": "いちばん好きなお祭りの食べ物", "question_en": "What's your favorite festival food?", "responses": ["I like <em>yakitori</em>.  It's always good."]},
	{"theme_jp": "いちばん好きなクラスメート", "question_en": "Who's your favorite classmate?", "responses": ["I like Edward Trout.  He likes sweets."]},
	{"theme_jp": "手伝い", "question_en": "How do you help your family?", "responses": ["I sometimes wash the dishes."]},
	{"theme_jp": "学校への行き方", "question_en": "How do you come to school?", "responses": ["I ride my bicycle to school.", "I walk to school.  It takes 15 minutes.", "I come to school by train."]},
	{"theme_jp": "いちばん好きなおもいで", "question_en": "What's your best memory?", "responses": ["I enjoyed Sports Day.  It was exciting.", "I ate a lot of mochi at the Mochi-making Festival."]},
	{"theme_jp": "あこがれな人", "question_en": "Who is your hero?", "responses": ["My hero is my mother.  She is smart."]},
	{"theme_jp": "いつもの朝食", "question_en": "What do you usually have for breakfast?", "responses": ["I usually have eggs and toast for breakfast.", "I never eat breakfast."]},
	{"theme_jp": "犬派? 猫派?", "question_en": "Which do you like, dogs or cats?", "responses": ["I like dogs.  Dogs are friendly.",  "I like cats.  They are cute."]},
	{"theme_jp": "習い事", "question_en": "Do you take any lessons after school?", "responses": ["I have a piano lesson every Saturday.", "I go to juku."]}
];
