export default [
	{"src": "badminton_ppqwi1gl.png","katakana": "キャン ユー プレイ バドミントン？", "english": "Can you play badminton?", "japanese": "バドミントンはできますか？"},
	{"src": "baseball_tvb2d7_m.png","katakana": "キャン ユー プレイ ベースボール？", "english": "Can you play baseball?", "japanese": "野球はできますか？"},
	{"src": "basketball_z8jus5p3.png","katakana": "キャン ユー プレイ バスケットボール？", "english": "Can you play basketball?", "japanese": "バスケットボールはできますか？"},
	{"src": "cartwheel.jpg","katakana": "キャン ユー ドゥー ア カートホイール？", "english": "Can you do a cartwheel?", "japanese": "側転はできますか？"},
	{"src": "cook_zok5bvfs.png","katakana": "キャン ユー クック？", "english": "Can you cook?", "japanese": "料理はできますか？"},
	{"src": "dance_o2r4qfrs.png","katakana": "キャン ユー ダンス？", "english": "Can you dance?", "japanese": "ダンスはできますか？"},
	{"src": "dodgeball_r86vrz57.png","katakana": "キャン ユー プレイ ドッジボール？", "english": "Can you play dodgeball?", "japanese": "ドッジボールはできますか？"},
	{"src": "draw.png","katakana": "キャン ユー ドロー ウェル？", "english": "Can you draw well?", "japanese": "絵は上手に描けますか？"},
	{"src": "drink_coffee.png","katakana": "キャン ユー ドリンク コーヒー？", "english": "Can you drink coffee?", "japanese": "コーヒーは飲めますか？"},
	{"src": "drum_ohljnhj4.png","katakana": "キャン ユー プレイ ザ ドラムス？", "english": "Can you play the drums?", "japanese": "太鼓は演奏できますか？"},
	{"src": "eat_piman.png","katakana": "キャン ユー イート グリーン ペッパー？", "english": "Can you eat green pepper?", "japanese": "ピーマンは食べられますか？"},
	{"src": "eat_umeboshi.png","katakana": "キャン ユー イート ウメボシ？", "english": "Can you eat umeboshi?", "japanese": "梅干しは食べられますか？"},
	//{"src": "fly.jpg","katakana": "キャン ユー フライ？", "english": "Can you fly?", "japanese": "飛べますか？"},
	{"src": "guitar__fom3i1k.png","katakana": "キャン ユー プレイ ザ ギター？", "english": "Can you play the guitar?", "japanese": "ギターは弾けますか？"},
	{"src": "ice_skating___01435x.png","katakana": "キャン ユー アイス スケート？", "english": "Can you ice skate?", "japanese": "アイススケートはできますか？"},
	{"src": "judo_r63rt_bw.png","katakana": "キャン ユー ドゥー ジュードー？", "english": "Can you do judo?", "japanese": "柔道はできますか？"},
	{"src": "jump.png","katakana": "キャン ユー ジャンプ ハイ？", "english": "Can you jump high?", "japanese": "高くジャンプできますか？"},
	{"src": "jump_rope_jmxciuz1.png","katakana": "キャン ユー ジャンプ ロープ？", "english": "Can you jump rope?", "japanese": "縄跳びはできますか？"},
	{"src": "natto_x7n82gbn.png","katakana": "キャン ユー イート ナットウ？", "english": "Can you eat natto?", "japanese": "納豆は食べられますか？"},
	{"src": "origami_8wvwws3b.png","katakana": "キャン ユー メイク オリガミ？", "english": "Can you make origami?", "japanese": "折り紙はできますか？"},
	{"src": "parkour.png","katakana": "キャン ユー ドゥー パルクール？", "english": "Can you do parkour?", "japanese": "パルクールはできますか？"},
	{"src": "play_kendama_8734rppz.png","katakana": "キャン ユー プレイ ケンダマ？", "english": "Can you play kendama?", "japanese": "けん玉はできますか？"},
	{"src": "play_soccer_9xub06lc.png","katakana": "キャン ユー プレイ サッカー？", "english": "Can you play soccer?", "japanese": "サッカーはできますか？"},
	{"src": "play_the_piano_akzussa2.png","katakana": "キャン ユー プレイ ザ ピアノ？", "english": "Can you play the piano?", "japanese": "ピアノは弾けますか？"},
	{"src": "play_the_recorder_3htp_2y2.png","katakana": "キャン ユー プレイ ザ リコーダー？", "english": "Can you play the recorder?", "japanese": "リコーダーは弾けますか？"},
	{"src": "ride_a_unicycle_f9rdo9ab.png","katakana": "キャン ユー ライド ア ユニサイクル？", "english": "Can you ride a unicycle?", "japanese": "一輪車に乗れますか？"},
	{"src": "ripstick.png","katakana": "キャン ユー ライド ア リップスティック？", "english": "Can you ride a ripstick?", "japanese": "リップスティックに乗れますか？"},
	{"src": "shiritori.png","katakana": "キャン ユー プレイ シリトリ？", "english": "Can you play shiritori?", "japanese": "しりとりはできますか？"},
	{"src": "sign_language.png","katakana": "キャン ユー ユース サイン ランゲージ？", "english": "Can you use sign language?", "japanese": "手話はできますか？"},
	{"src": "sing.png","katakana": "キャン ユー シング？", "english": "Can you sing?", "japanese": "歌はできますか？"},
	{"src": "skiing_7jj8atz_.png","katakana": "キャン ユー スキー？", "english": "Can you ski?", "japanese": "スキーはできますか？"},
	{"src": "soroban.jpg","katakana": "キャン ユー ドゥー ソロバン？", "english": "Can you do soroban?", "japanese": "そろばんはできますか？"},
	//{"src": "speak_english.jpg","katakana": "キャン ユー スピーク イングリッシュ？", "english": "Can you speak English?", "japanese": "英語は話せますか？"},
	{"src": "swim_b07iclvo.png","katakana": "キャン ユー スイム？", "english": "Can you swim?", "japanese": "泳げますか？"},
	{"src": "tennis_z9g7luke.png","katakana": "キャン ユー プレイ テニス？", "english": "Can you play tennis?", "japanese": "テニスはできますか？"},
	{"src": "tetsubo.png","katakana": "キャン ユー ドゥ テツボウ？", "english": "Can you do tetsubo?", "japanese": "鉄棒はできますか？"},
	{"src": "typing.png","katakana": "キャン ユー タイプ ファスト？", "english": "Can you type fast?", "japanese": "速くタイピングできますか？"},
	{"src": "video_game_yc980ki5.png","katakana": "キャン ユー プレイ ビデオ ゲームス？", "english": "Can you play video games?", "japanese": "テレビゲームはできますか？"},
	{"src": "volleyball__z47fwgh.png","katakana": "キャン ユー プレイ バレーボール？", "english": "Can you play volleyball?", "japanese": "バレーボールはできますか？"}//,
	//{"src": "writing_english.jpg","katakana": "キャン ユー ライト イングリッシュ？", "english": "Can you write English?", "japanese": "英語は書けますか？"},
]
