export default [
{"country_code": "ar", "english": "Argentina", "src": "argentina_banknote.jpg"},
{"country_code": "au", "english": "Australia", "src": "australia_banknote.jpg"},
{"country_code": "bd", "english": "Bangladesh", "src": "bangladesh_banknote.jpg"},
{"country_code": "br", "english": "Brazil", "src": "brazil_banknote.jpg"},
{"country_code": "ca", "english": "Canada", "src": "canada_banknote.jpg"},
{"country_code": "cn", "english": "China", "src": "china_banknote.jpg"},
{"country_code": "cg", "english": "Congo", "src": "congo_banknote.jpg"},
{"country_code": "eg", "english": "Egypt", "src": "egypt_banknote.jpg"},
{"country_code": "et", "english": "Ethiopia", "src": "ethiopia_banknote.jpg"},
{"country_code": "eu", "english": "Euro", "src": "euro_banknote.jpg"},
{"country_code": "gb", "english": "the U.K.", "src": "great_britain_banknote.jpg"},
{"country_code": "in", "english": "India", "src": "india_banknote.jpg"},
{"country_code": "id", "english": "Indonesia", "src": "indonesia_banknote.jpg"},
{"country_code": "ir", "english": "Iran", "src": "iran_banknote.jpg"},
{"country_code": "jp", "english": "Japan", "src": "japan_banknote.jpg"},
{"country_code": "ke", "english": "Kenya", "src": "kenya_banknote.jpg"},
{"country_code": "kr", "english": "Korea", "src": "korea_banknote.jpg"},
{"country_code": "my", "english": "Malaysia", "src": "malaysia_banknote.jpg"},
{"country_code": "mx", "english": "Mexico", "src": "mexico_banknote.jpg"},
{"country_code": "mn", "english": "Mongolia", "src": "mongolia_banknote.jpg"},
{"country_code": "np", "english": "Nepal", "src": "nepal_banknote.jpg"},
{"country_code": "nz", "english": "New Zealand", "src": "new_zealand_banknote.jpg"},
{"country_code": "ng", "english": "Nigeria", "src": "nigeria_banknote.jpg"},
{"country_code": "no", "english": "Norway", "src": "norway_banknote.jpg"},
{"country_code": "pk", "english": "Pakistan", "src": "pakistan_banknote.jpg"},
{"country_code": "pe", "english": "Peru", "src": "peru_banknote.jpg"},
{"country_code": "ph", "english": "Phillipines", "src": "phillipines_banknote.jpg"},
{"country_code": "pl", "english": "Poland", "src": "poland_banknote.jpg"},
{"country_code": "ru", "english": "Russia", "src": "russia_banknote.jpg"},
{"country_code": "sa", "english": "Saudi Arabia", "src": "saudi_arabia_banknote.jpg"},
{"country_code": "sg", "english": "Singapore", "src": "singapore_banknote.jpg"},
{"country_code": "za", "english": "South Africa", "src": "south_africa_banknote.jpg"},
{"country_code": "se", "english": "Sweden", "src": "sweden_banknote.jpg"},
{"country_code": "ch", "english": "Switzerland", "src": "switzerland_banknote.jpg"},
{"country_code": "tz", "english": "Tanzania", "src": "tanzania_banknote.jpg"},
{"country_code": "th", "english": "Thailand", "src": "thailand_banknote.jpg"},
{"country_code": "tr", "english": "Turkey", "src": "turkey_banknote.jpg"},
{"country_code": "ae", "english": "U.A.E.", "src": "uae_banknote.jpg"},
{"country_code": "us", "english": "the U.S.A.", "src": "usa_banknote.jpg"},
{"country_code": "vn", "english": "Vietnam", "src": "vietnam_banknote.jpg"}
];
